project:
  type: website

website:
  title: "Sum Yee Chong | Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scho0107
format:
  html:
    theme: cosmo
    css: styles.css



