{
  "hash": "9e51c34af0ced575ccc5f878767a01c6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Germany had fewer hospital infections per patient, but more across the population\"\nauthor: \"Sum Yee Chong\"\ndate: \"2026-10-05\"\ncategories: [health, hospitals, data story]\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\nGermany had fewer hospital infections per 100 patients than the European average in 2011–12. But when infections were measured across the population, Germany had more. Researchers linked this difference to Germany’s high level of hospital use.\n\n## Nearly half a million hospital infections in one year\n\nSome patients pick up a new infection while receiving hospital care, separate from the illness that brought them to hospital in the first place. These are known as healthcare-associated infections. In 2011, Germany had an estimated 478,000 cases of five common types, with around 16,000 deaths attributed to them (Zacher et al., 2019). Earlier research cited in the study suggested that around 20–30% of these infections could be prevented.\n\nComparing hospital safety between countries is not as simple as it might seem, because the result can change depending on what is being measured. This post looks at two questions:\n\n1. Is Germany's hospital infection problem worse than the European average?\n2. Is the most common infection also the most harmful?\n\n## Where the numbers come from\n\nThe figures come from a study by Zacher and colleagues, published in *Eurosurveillance* (Zacher et al., 2019). The study used hospital survey data collected in 2011–12 by the European Centre for Disease Prevention and Control (ECDC). In each hospital, researchers recorded which patients had an infection on the day of the survey.\n\nThe German sample included about 9,600 patients from 46 randomly selected hospitals. The European average was based on about 274,000 patients from 1,149 hospitals across the European Union and European Economic Area (EU/EEA).\n\nThe researchers used these survey results to estimate how many new infections occurred over a year. They also estimated the harm caused by these infections using disability-adjusted life years (DALYs), a measure of healthy years lost through early death or time lived in poor health. In other words, an infection that causes little lasting harm does not count the same as one that causes severe illness or death.\n\n## Below the European average per patient, above it across the population\n\n\n::: {#tbl-compare .cell tbl-cap='Germany had fewer infections per hospital patient but more per 100,000 people than the European average, 2011–12.'}\n::: {.cell-output-display}\n\n\n|How it is counted                        | Germany| European average|What the comparison suggests |\n|:----------------------------------------|-------:|----------------:|:----------------------------|\n|New infections per 100 hospital patients |     2.4|              2.8|Lower in Germany             |\n|New infections per 100,000 people        |     592|              468|Higher in Germany            |\n|Healthy years lost per 100,000 people    |     308|              290|Difference uncertain         |\n\n\n:::\n:::\n\n*Note: The study reported substantial uncertainty around the comparison in healthy years lost.*\n\nWhether Germany looks better or worse depends on how infections are counted (@tbl-compare). For every 100 hospital patients, Germany had 2.4 new infections, compared with the European average of 2.8. But when the same infections were counted across the population, the order flipped: Germany had 592 new infections per 100,000 people, compared with the European average of 468.\n\nHow could both be true? The researchers linked this reversal to Germany's high level of hospital use. At the time, Germany had the highest number of acute-care hospital beds in Europe and the second-highest rate of hospital patients per 1,000 people among 34 OECD countries. They also suggested that good hygiene may partly explain Germany's lower rate per patient. At the same time, the large number of people passing through hospitals could help explain why infections were more common across the population.\n\nSo, was Germany's problem worse? Measured across the population, there were more infections. Whether this led to greater overall health loss was less clear. Germany lost an estimated 308 healthy years per 100,000 people, compared with the European average of 290, but the uncertainty around this comparison was wide.\n\n## The most common infection was not the most harmful\n\nCounting cases treats every infection the same. Looking at healthy years lost shows which infections caused the greatest health loss (@fig-shares).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Pneumonia and bloodstream infections (blue) made up a larger share of healthy years lost than of infections. Germany, 2011. Shares calculated from Zacher et al. (2019).](index_files/figure-html/fig-shares-1.png){#fig-shares width=768}\n:::\n:::\n\n\nUrinary tract infections were the most common, with about 214,000 cases, but they accounted for only around 27% of healthy years lost. Bloodstream infections were much less common, with about 27,000 cases, yet they still accounted for around 23% of healthy years lost.\n\n::: {.finding}\nPneumonia and bloodstream infections made up only about 28% of cases, but accounted for about 51% of healthy years lost.\n:::\n\nSo the answer to the second question is no. Counting cases alone does not show which infections cause the most harm.\n\n## How you count changes the answer\n\nWas Germany's hospital infection problem worse than the European average? It depends on how the infections are counted. Germany had fewer infections per hospital patient, but more when infections were measured across the population. The researchers linked this difference to Germany's high level of hospital use. Whether Germany also experienced greater overall health loss, however, was less clear.\n\nWas the most common infection also the most harmful? No. Urinary tract infections were the most common, but pneumonia and bloodstream infections together accounted for about half of the healthy years lost.\n\nThere are two important limitations to keep in mind. First, the data come from 2011–12, so the results should not be taken as a picture of hospital infections in Germany today. Later surveys in 2016 suggested that urinary tract infections had become less common in German hospitals, while *C. difficile* infections had become more common (Zacher et al., 2019). Second, the study covered five infection types, which made up about 79% of hospital infections in the ECDC survey, so it did not capture every type of infection.\n\nThe next time you see a headline saying that one country has more hospital infections than another, check how the infections were counted: per hospital patient, or across the whole population.\n\n## References\n\nZacher, B., Haller, S., Willrich, N., Walter, J., Abu Sin, M., Cassini, A., Plachouras, D., Suetens, C., Behnke, M., Gastmeier, P., Wieler, L. H., & Eckmanns, T. (2019). Application of a new methodology and R package reveals a high burden of healthcare-associated infections (HAI) in Germany compared to the average in the European Union/European Economic Area, 2011 to 2012. *Eurosurveillance, 24*(46).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}